apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: raccooncluster
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
  kubeProxyMode: "ipvs"
  disableDefaultCNI: true
nodes:
- role: control-plane
- role: worker
