---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: raccoon
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - get
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: raccoon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: raccoon
subjects:
- kind: ServiceAccount
  name: raccoon
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: raccoon
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: raccoon
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-raccoon-cfg
  namespace: kube-system
  labels:
    tier: node
    app: raccoon
data:
  cni-conf.json: |
    {
      "name": "raccoon",
      "cniVersion": "0.4.0",
      "type": "raccoon",
      "dataDir": "/var/lib/cni/networks"
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-raccoon-ds
  namespace: kube-system
  labels:
    tier: node
    app: raccoon
spec:
  selector:
    matchLabels:
      app: raccoon
  template:
    metadata:
      labels:
        tier: node
        app: raccoon
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: raccoon
      initContainers:
      - name: install-cni-plugin
        image: layzer/raccoon:0952c9b
        command:
        - cp
        args:
        - -f
        - /raccoon
        - /opt/cni/bin/raccoon
        volumeMounts:
        - name: cni-plugin
          mountPath: /opt/cni/bin
      - name: install-cni
        image: layzer/raccoon:0952c9b
        command:
        - cp
        args:
        - -f
        - /etc/kube-raccoon/cni-conf.json
        - /etc/cni/net.d/10-raccoon.conf
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: raccoon-cfg
          mountPath: /etc/kube-raccoon/
      containers:
      - name: kube-raccoon
        image: layzer/raccoon:0952c9b
        command:
        - /raccoond
        args:
        # get cluster cidr from kube-controller-manager
        - --cluster-cidr=10.244.0.0/16
        - --node=$(NODE_NAME)
        - --enable-iptables
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: run
          mountPath: /run/raccoon
        - name: raccoon-cfg
          mountPath: /etc/kube-raccoon/
      volumes:
      - name: run
        hostPath:
          path: /run/raccoon
      - name: cni-plugin
        hostPath:
          path: /opt/cni/bin
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: raccoon-cfg
        configMap:
          name: kube-raccoon-cfg